/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

// Placeholder types - run `npm run generate:types` to generate actual types
export interface Config {
	collections: {
		users: User
		media: Media
		brands: Brand
		models: Model
		cars: Car
		locations: Location
		leads: Lead
		pages: Page
	}
	globals: {
		settings: Settings
		header: Header
		footer: Footer
	}
}

export interface User {
	id: string
	email: string
	role: 'admin' | 'manager'
	name?: string
}

export interface Media {
	id: string
	alt: string
	url: string
	filename: string
	mimeType: string
	filesize: number
	width?: number
	height?: number
}

export interface Brand {
	id: string
	title: string
	slug: string
	logo?: Media | string
	country?: string
	description?: any
	shortDescription?: string
	order?: number
	isPublished?: boolean
	seo?: SEO
}

export interface Model {
	id: string
	title: string
	slug: string
	brand: Brand | string
	image?: Media | string
	shortDescription?: string
	description?: any
	bodyType?: string
	order?: number
	isPublished?: boolean
	seo?: SEO
}

export interface Car {
	id: string
	title: string
	slug: string
	brand: Brand | string
	model: Model | string
	price: number
	oldPrice?: number
	status: 'in_stock' | 'on_order' | 'sold' | 'reserved'
	vin?: string
	stockNumber?: string
	specifications?: {
		year?: number
		mileage?: number
		engineType?: string
		power?: number
		battery?: string
		range?: number
		drivetrain?: string
		transmission?: string
		color?: string
		interiorColor?: string
	}
	gallery?: {image: Media | string}[]
	mainImage?: Media | string
	location?: Location | string
	shortDescription?: string
	description?: any
	tags?: string[]
	isFeatured?: boolean
	isPublished?: boolean
	seo?: SEO
}

export interface Location {
	id: string
	title: string
	address: string
	city?: string
	phone?: string
	email?: string
	workingHours?: string
	mapCoordinates?: {lat?: number; lng?: number}
	image?: Media | string
	order?: number
}

export interface Lead {
	id: string
	type: 'callback' | 'contact' | 'car_inquiry' | 'credit' | 'leasing'
	name: string
	phone: string
	email?: string
	comment?: string
	sourceUrl?: string
	utmSource?: string
	utmMedium?: string
	utmCampaign?: string
	utmTerm?: string
	utmContent?: string
	car?: Car | string
	brand?: Brand | string
	model?: Model | string
	carTitleSnapshot?: string
	carUrlSnapshot?: string
	vinSnapshot?: string
	stockNumberSnapshot?: string
	leadStatus?: 'new' | 'processing' | 'completed' | 'rejected'
	createdAt: string
	updatedAt: string
}

export interface Page {
	id: string
	title: string
	slug: string
	content?: any
	isPublished?: boolean
	seo?: SEO
}

export interface SEO {
	title?: string
	description?: string
	image?: Media | string
}

export interface Settings {
	siteName?: string
	siteDescription?: string
	adminEmail?: string
	phone?: string
	additionalPhones?: {phone?: string; label?: string}[]
	email?: string
	address?: string
	workingHours?: string
	socialLinks?: {
		instagram?: string
		facebook?: string
		telegram?: string
		youtube?: string
		viber?: string
	}
	scripts?: {
		googleAnalytics?: string
		facebookPixel?: string
	}
}

export interface Header {
	logo?: Media | string
	navItems?: {
		label: string
		url: string
		children?: {label: string; url: string}[]
	}[]
	ctaText?: string
	ctaUrl?: string
}

export interface Footer {
	columns?: {
		title: string
		links?: {label: string; url: string}[]
	}[]
	bottomText?: string
	copyright?: string
}
